export type ToolMeta = {
  slug: string;
  title: string;
  description: string;
  tags?: string[];
};

export const TOOL_META: ToolMeta[] = [
  // Images
  { slug: "image-studio", title: "Image Studio", description: "All image tools in one workspace.", tags: ["studio"] },
  { slug: "image-resizer", title: "Image Resizer", description: "Resize images and download PNG.", tags: ["image"] },
  { slug: "background-remover", title: "Background Remover", description: "Remove backgrounds with color-keying.", tags: ["image"] },
  { slug: "image-color-picker", title: "Image Color Picker", description: "Pick multiple colors and export a palette.", tags: ["image"] },
  { slug: "logo-background-tester", title: "Logo Background Tester", description: "Preview logos on multiple backgrounds.", tags: ["image"] },
  { slug: "brand-mockup-generator", title: "Brand Mockup Generator", description: "Generate social banners from brand assets.", tags: ["image"] },
  { slug: "ocr-pro", title: "OCR Pro", description: "Extract text from images locally.", tags: ["image"] },
  { slug: "image-compressor", title: "Image Compressor", description: "Compress images to JPG.", tags: ["image"] },
  { slug: "jpg-to-png", title: "JPG to PNG", description: "Convert JPG → PNG.", tags: ["image"] },
  { slug: "png-to-jpg", title: "PNG to JPG", description: "Convert PNG → JPG.", tags: ["image"] },
  { slug: "favicon-generator", title: "Favicon Generator", description: "Generate favicon sizes.", tags: ["image"] },
  { slug: "svg-optimizer", title: "SVG Optimizer", description: "Optimize SVG files.", tags: ["image"] },
  { slug: "icon-pack-previewer", title: "Icon Pack Previewer", description: "Preview SVG/PNG icon packs.", tags: ["image"] },
  { slug: "image-metadata", title: "Image Metadata Viewer", description: "View EXIF image metadata.", tags: ["image"] },
  { slug: "image-format-converter", title: "Image Format Converter", description: "Convert images to JPG, PNG, WebP, or AVIF.", tags: ["image"] },
  { slug: "video-studio", title: "Video Studio", description: "Edit, extract, and convert videos locally.", tags: ["studio"] },
  { slug: "video-storyboard", title: "Video Storyboard", description: "Create a timestamped storyboard grid.", tags: ["video"] },
  { slug: "video-to-images", title: "Video to Images", description: "Extract video frames into images.", tags: ["video"] },
  { slug: "images-to-video", title: "Images to Video", description: "Combine images into a WebM video.", tags: ["video"] },
  { slug: "video-trimmer", title: "Video Trimmer", description: "Trim video clips in your browser.", tags: ["video"] },
  { slug: "video-speed-changer", title: "Video Speed Changer", description: "Change playback speed with FFmpeg.", tags: ["video"] },
  { slug: "video-thumbnailer", title: "Video Thumbnailer", description: "Create a video contact sheet.", tags: ["video"] },
  { slug: "video-audio-extractor", title: "Video Audio Extractor", description: "Extract audio from a video.", tags: ["video"] },
  { slug: "video-subtitle-burner", title: "Video Subtitle Burner", description: "Burn SRT subtitles into a video.", tags: ["video"] },
  { slug: "video-color-lut", title: "Video Color LUT Preview", description: "Apply cinematic color presets.", tags: ["video"] },
  { slug: "video-to-gif", title: "Video to GIF", description: "Convert a video clip into a GIF.", tags: ["video"] },
  { slug: "video-to-mp4", title: "Video to MP4", description: "Re-encode a video to MP4.", tags: ["video"] },
  { slug: "images-to-gif", title: "Images to GIF", description: "Create an animated GIF from images.", tags: ["image"] },
  { slug: "gif-optimizer", title: "GIF Optimizer", description: "Reduce GIF size by lowering FPS/scale.", tags: ["image"] },
  { slug: "sprite-sheet-builder", title: "Sprite Sheet Builder", description: "Combine images into a sprite sheet.", tags: ["image"] },
  { slug: "ocr-reader", title: "OCR Reader", description: "Extract text from images.", tags: ["image"] },

  // PDF
  { slug: "pdf-studio", title: "PDF Studio", description: "All-in-one PDF workspace.", tags: ["studio"] },
  { slug: "merge-pdfs", title: "Merge PDFs", description: "Merge multiple PDFs into one.", tags: ["pdf"] },
  { slug: "split-pdfs", title: "Split PDFs", description: "Split a PDF into separate pages.", tags: ["pdf"] },
  { slug: "compress-pdfs", title: "Compress PDFs", description: "Compress PDF files locally.", tags: ["pdf"] },
  { slug: "pdf-to-images", title: "PDF to Images", description: "Convert each PDF page to PNG.", tags: ["pdf"] },
  { slug: "pdf-to-jpg", title: "PDF to JPG", description: "Convert each PDF page to JPG.", tags: ["pdf"] },
  { slug: "pdf-thumbnailer", title: "PDF Thumbnailer", description: "Generate page thumbnails.", tags: ["pdf"] },
  { slug: "pdf-thumbnail-zip", title: "PDF Thumbnails ZIP", description: "Download thumbnails as a ZIP.", tags: ["pdf"] },
  { slug: "pdf-page-extractor", title: "PDF Page Extractor", description: "Extract a single page as PDF/PNG/JPG.", tags: ["pdf"] },
  { slug: "pdf-file-analyzer", title: "PDF File Size Analyzer", description: "Inspect page sizes and largest images.", tags: ["pdf"] },
  { slug: "images-to-pdf", title: "Images to PDF", description: "Convert images into a single PDF.", tags: ["pdf"] },
  { slug: "pdf-page-cropper", title: "PDF Crop & Margins", description: "Trim page margins or crop pages.", tags: ["pdf"] },
  { slug: "pdf-page-size", title: "PDF Page Size Converter", description: "Convert pages to A4/Letter/Legal.", tags: ["pdf"] },
  { slug: "pdf-grayscale", title: "PDF Grayscale", description: "Flatten pages to grayscale.", tags: ["pdf"] },
  { slug: "pdf-form-filler", title: "PDF Form Filler", description: "Fill PDF form fields locally.", tags: ["pdf"] },
  { slug: "split-pdf", title: "Split PDF", description: "Split a PDF into pages or ranges.", tags: ["pdf"] },
  { slug: "compress-pdf", title: "Compress PDF", description: "Re-save a PDF to reduce size.", tags: ["pdf"] },
  { slug: "rotate-pdf", title: "Rotate PDF", description: "Rotate PDF pages 90/180/270 degrees.", tags: ["pdf"] },
  { slug: "reorder-pdf-pages", title: "Reorder PDF Pages", description: "Reorder pages with a custom list.", tags: ["pdf"] },
  { slug: "remove-pdf-pages", title: "Remove PDF Pages", description: "Remove selected pages from a PDF.", tags: ["pdf"] },
  { slug: "extract-pdf-pages", title: "Extract PDF Pages", description: "Extract pages into a new PDF.", tags: ["pdf"] },
  { slug: "pdf-to-text", title: "PDF to Text", description: "Extract text from a PDF.", tags: ["pdf"] },
  { slug: "pdf-to-html", title: "PDF to HTML", description: "Extract PDF text into basic HTML.", tags: ["pdf"] },
  { slug: "pdf-watermark", title: "PDF Watermark", description: "Add a text watermark to pages.", tags: ["pdf"] },
  { slug: "pdf-watermark-designer", title: "PDF Watermark Designer", description: "Drag and design watermarks.", tags: ["pdf"] },
  { slug: "pdf-page-numbers", title: "PDF Page Numbers", description: "Add page numbers to each page.", tags: ["pdf"] },
  { slug: "pdf-metadata-editor", title: "PDF Metadata Editor", description: "Edit PDF title/author/keywords.", tags: ["pdf"] },
  { slug: "pdf-annotator", title: "PDF Annotator", description: "Add a note overlay to a page.", tags: ["pdf"] },
  { slug: "protect-pdf", title: "Protect PDF", description: "Password protect a PDF.", tags: ["pdf"] },
  { slug: "unlock-pdf", title: "Unlock PDF", description: "Remove PDF password protection.", tags: ["pdf"] },
  { slug: "pdf-redactor", title: "PDF Redactor", description: "Cover content with redaction blocks.", tags: ["pdf"] },
  { slug: "pdf-redact-by-color", title: "PDF Redact by Color", description: "Redact areas by color matching.", tags: ["pdf"] },
  { slug: "sign-pdf", title: "Sign PDF", description: "Add a visual signature.", tags: ["pdf"] },
  { slug: "pdf-split-bookmarks", title: "PDF Split by Bookmarks", description: "Split by bookmark outline.", tags: ["pdf"] },
  { slug: "pdf-split-blank", title: "Smart PDF Split (Blank Pages)", description: "Split using blank pages.", tags: ["pdf"] },

  // Encode / Data
  { slug: "dev-studio", title: "Developer Studio", description: "All developer utilities in one workspace.", tags: ["studio"] },
  { slug: "base64", title: "Base64 Encoder/Decoder", description: "Encode/decode Base64.", tags: ["dev"] },
  { slug: "jwt-decoder", title: "JWT Decoder", description: "Decode JWT header and payload locally.", tags: ["dev"] },
  { slug: "regex-tester", title: "Regex Tester", description: "Test regex patterns and preview matches.", tags: ["dev"] },
  { slug: "hash-generator", title: "Hash Generator", description: "Generate hashes locally using WebCrypto.", tags: ["dev"] },
  { slug: "cron-generator", title: "Cron Generator", description: "Build cron expressions visually.", tags: ["dev"] },
  { slug: "url-encoder", title: "URL Encoder/Decoder", description: "Encode/decode URL components.", tags: ["dev"] },
  { slug: "json-formatter", title: "JSON Formatter", description: "Validate and format JSON.", tags: ["dev"] },
  { slug: "json-diff-patch", title: "JSON Diff & Patch", description: "Compare JSON and generate patch ops.", tags: ["dev"] },
  { slug: "uuid-ulid-generator", title: "UUID / ULID Generator", description: "Generate UUID v4 and ULID values.", tags: ["dev"] },
  { slug: "hmac-signer", title: "HMAC Signer", description: "Sign and verify HMAC signatures.", tags: ["dev"] },
  { slug: "env-var-validator", title: "Env Var Validator", description: "Validate .env files for issues.", tags: ["dev"] },
  { slug: "api-request-builder", title: "API Request Builder", description: "Build requests and export curl.", tags: ["dev"] },

  // Text
  { slug: "text-studio", title: "Text Studio", description: "Transform, analyze, and generate text.", tags: ["studio"] },
  { slug: "case-converter", title: "Case Converter", description: "Convert between case styles.", tags: ["text"] },
  { slug: "text-case-converter", title: "Text Case Converter", description: "Convert between case styles.", tags: ["text"] },
  { slug: "word-counter", title: "Word & Character Counter", description: "Count words/chars/lines.", tags: ["text"] },
  { slug: "find-replace", title: "Find & Replace", description: "Find & replace text (regex optional).", tags: ["text"] },
  { slug: "lorem-ipsum", title: "Lorem Ipsum", description: "Generate placeholder text.", tags: ["text"] },
  { slug: "slug-generator", title: "Slug Generator", description: "Generate URL-friendly slugs.", tags: ["text"] },
  { slug: "text-statistics", title: "Text Statistics", description: "Reading time and text metrics.", tags: ["text"] },
  { slug: "remove-duplicate-lines", title: "Remove Duplicate Lines", description: "Deduplicate text lines.", tags: ["text"] },
  { slug: "sort-lines", title: "Sort Lines", description: "Sort lines alphabetically.", tags: ["text"] },
  { slug: "whitespace-cleaner", title: "Whitespace Cleaner", description: "Normalize whitespace and line breaks.", tags: ["text"] },

  // Color
  { slug: "color-studio", title: "Color Studio", description: "Build palettes, gradients, and brand tokens.", tags: ["studio"] },
  { slug: "color-picker", title: "Color Picker", description: "Pick a color and copy hex.", tags: ["color"] },
  { slug: "contrast-checker", title: "Contrast Checker", description: "WCAG contrast ratio checks.", tags: ["color"] },
  { slug: "color-palette-generator", title: "Color Palette Generator", description: "Generate color palettes.", tags: ["color"] },
  { slug: "gradient-builder", title: "Gradient Builder", description: "Build CSS gradients visually.", tags: ["color"] },
  { slug: "color-harmony-generator", title: "Color Harmony Generator", description: "Complementary and triadic palettes.", tags: ["color"] },
  { slug: "gradient-gallery", title: "Gradient Gallery", description: "Generate a gradient preset gallery.", tags: ["color"] },
  { slug: "brand-color-tokens", title: "Brand Color Tokens", description: "Generate CSS/JSON color tokens.", tags: ["color"] },
  { slug: "type-scale-builder", title: "Type Scale Builder", description: "Build modular typography scales.", tags: ["text"] },

  // Conversions
  { slug: "unit-converter", title: "Unit Converter", description: "Length/weight/temp conversions.", tags: ["utility"] },
  { slug: "audio-studio", title: "Audio Studio", description: "Clean, analyze, and convert audio files locally.", tags: ["studio"] },
  { slug: "audio-waveform-generator", title: "Audio Waveform Generator", description: "Generate a waveform image from audio.", tags: ["utility"] },
  { slug: "waveform-preset-exporter", title: "Waveform Preset Exporter", description: "Export waveform presets.", tags: ["utility"] },
  { slug: "audio-normalizer", title: "Audio Normalizer", description: "Normalize loudness with LUFS target.", tags: ["utility"] },
  { slug: "voice-cleaner", title: "AI-Free Voice Cleaner", description: "Noise gate + EQ presets for speech.", tags: ["utility"] },
  { slug: "audio-segmenter", title: "Audio Segmenter", description: "Split audio on silence into clips.", tags: ["utility"] },
  { slug: "audio-to-wav", title: "Audio to WAV", description: "Convert audio or video files into WAV.", tags: ["utility"] },
  { slug: "audio-to-ogg", title: "Audio to OGG", description: "Re-encode media to Opus (OGG/WebM).", tags: ["utility"] },
  { slug: "audio-to-mp3", title: "Audio to MP3", description: "Convert media files into MP3 audio.", tags: ["utility"] },
  { slug: "media-metadata", title: "Media Metadata Viewer", description: "Inspect audio/video metadata locally.", tags: ["utility"] },
  { slug: "url-query-builder", title: "URL Query Builder", description: "Parse and build URL queries.", tags: ["utility"] },

  // Batch 1
  { slug: "password-generator", title: "Password Generator", description: "Generate strong passwords locally.", tags: ["dev"] },
  { slug: "markdown-to-html", title: "Markdown → HTML", description: "Convert Markdown to HTML.", tags: ["text"] },
  { slug: "html-to-markdown", title: "HTML → Markdown", description: "Convert HTML to Markdown.", tags: ["text"] },
  { slug: "data-studio", title: "Data Studio", description: "Convert and explore data files locally.", tags: ["studio"] },
  { slug: "csv-to-json", title: "CSV → JSON", description: "Convert CSV into JSON.", tags: ["data"] },
  { slug: "csv-profiler", title: "CSV Profiler", description: "Profile columns for types and outliers.", tags: ["data"] },
  { slug: "json-to-csv", title: "JSON → CSV", description: "Convert JSON into CSV.", tags: ["data"] },
  { slug: "yaml-json", title: "YAML ⇄ JSON", description: "Convert YAML and JSON.", tags: ["data"] },
  { slug: "xml-json", title: "XML ⇄ JSON", description: "Convert XML and JSON.", tags: ["data"] },
  { slug: "base-number-converter", title: "Base Number Converter", description: "Binary / Hex / Decimal conversion.", tags: ["data"] },
  { slug: "json-table-viewer", title: "JSON ↔ Table", description: "Edit JSON arrays in a table view.", tags: ["data"] },
  { slug: "qr-code-generator", title: "QR Code Generator", description: "Generate a QR code PNG.", tags: ["utility"] },
  { slug: "qr-code-scanner", title: "QR Code Scanner", description: "Scan QR codes using your camera.", tags: ["utility"] },
  { slug: "barcode-generator", title: "Barcode Generator", description: "Generate CODE128/EAN13 barcodes.", tags: ["utility"] },
  { slug: "text-diff-checker", title: "Text Diff Checker", description: "Compare two texts line-by-line.", tags: ["text"] },

  // Batch 2
  { slug: "time-zone-converter", title: "Time Zone Converter", description: "Convert a date/time across time zones.", tags: ["utility"] },
  { slug: "countdown-timer", title: "Countdown Timer", description: "Start/pause/reset a countdown.", tags: ["utility"] },
  { slug: "stopwatch", title: "Stopwatch", description: "Stopwatch with laps.", tags: ["utility"] },
  { slug: "pomodoro-timer", title: "Pomodoro Timer", description: "Work/break timer.", tags: ["utility"] },
  { slug: "random-picker", title: "Random Picker", description: "Pick a random item from a list.", tags: ["fun"] },
  { slug: "wheel-spinner", title: "Wheel Spinner", description: "Spin a list and land on a winner.", tags: ["fun"] },
  { slug: "dice-roller", title: "Dice Roller", description: "Roll virtual dice.", tags: ["fun"] },
  { slug: "random-name-generator", title: "Random Name Generator", description: "Generate random names.", tags: ["fun"] },
  { slug: "magic-8-ball", title: "Magic 8 Ball", description: "Shake for a classic Magic 8 Ball response.", tags: ["fun"] },
  { slug: "coin-flip", title: "Coin Flip", description: "Flip a coin for heads or tails.", tags: ["fun"] },
  { slug: "yes-no-oracle", title: "Yes / No Oracle", description: "Get a quick yes/no answer.", tags: ["fun"] },
  { slug: "random-number-generator", title: "Random Number Generator", description: "Generate random numbers in a range.", tags: ["fun"] },
  { slug: "truth-or-dare", title: "Truth or Dare", description: "Get a truth or dare prompt.", tags: ["fun"] },
  { slug: "would-you-rather", title: "Would You Rather", description: "Pick between two scenarios.", tags: ["fun"] },
  { slug: "nickname-generator", title: "Nickname Generator", description: "Generate playful nicknames.", tags: ["fun"] },
  { slug: "username-generator", title: "Username Generator", description: "Generate username ideas.", tags: ["fun"] },
  { slug: "fun-fact-generator", title: "Fun Fact Generator", description: "Get a random fun fact.", tags: ["fun"] },
  { slug: "emoji-generator", title: "Emoji Generator", description: "Generate random emojis.", tags: ["fun"] },
  { slug: "emoji-combiner", title: "Emoji Combiner", description: "Combine two emojis.", tags: ["fun"] },
  { slug: "ascii-face-generator", title: "ASCII Face Generator", description: "Generate ASCII faces.", tags: ["fun"] },
  { slug: "excuse-generator", title: "Excuse Generator", description: "Generate a playful excuse.", tags: ["fun"] },
  { slug: "compliment-generator", title: "Compliment Generator", description: "Generate a quick compliment.", tags: ["fun"] },
  { slug: "startup-name-generator", title: "Startup Name Generator", description: "Generate startup name ideas.", tags: ["fun"] },
  { slug: "li-distinction-tester", title: "L/I Distinction Tester", description: "Spot confusing I vs l.", tags: ["dev"] },
  { slug: "file-corrupter", title: "File Corrupter", description: "Corrupt a file for QA testing.", tags: ["dev"] },
  { slug: "ascii-art-generator", title: "ASCII Art Generator", description: "Big ASCII banner from text.", tags: ["text"] },
];

export const TOOL_SLUGS: string[] = TOOL_META.map((t) => t.slug);
